#!/usr/bin/env python3
"""Deterministic judge-loop worker for Luna-owned review phases."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import subprocess
import sys
import time

SCRIPT_DIR = Path(__file__).resolve().parent
WORKSPACE = SCRIPT_DIR.parent.parent
sys.path.insert(0, str(SCRIPT_DIR))

from mc_control import (
    LUNA_REVIEW_PHASES,
    PRIMARY_CHANNEL,
    claim_review,
    is_actionable_review_task,
    is_claim_active,
    load_metrics,
    metrics_increment,
    metrics_record_cron,
    metrics_record_phase_transition,
    normalize_status,
    normalize_workflow,
    plan_artifact_path,
    save_metrics,
    task_fields,
    task_phase,
    task_phase_owner,
    task_workflow,
    to_iso,
)

MC_CLIENT = os.environ.get("MC_CLIENT", str(WORKSPACE / "scripts" / "mc-client.sh"))
OPENCLAW_BIN = os.environ.get("OPENCLAW_BIN", "openclaw")
OPENCLAW_CONFIG = os.environ.get("OPENCLAW_CONFIG", "/home/openclaw/.openclaw/openclaw.json")
GATEWAY_URL = os.environ.get("MC_GATEWAY_URL", "ws://127.0.0.1:18789")
METRICS_FILE = WORKSPACE / "state" / "control-loop-metrics.json"
LEASE_MINUTES = int(os.environ.get("MC_REVIEW_LEASE_MINUTES", "20"))


def run(cmd: list[str], timeout: int = 20) -> str:
    proc = subprocess.run(cmd, text=True, capture_output=True, timeout=timeout)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or proc.stdout.strip() or "command failed")
    return proc.stdout.strip()


def mc_list_tasks() -> list[dict]:
    raw = run([MC_CLIENT, "list-tasks"])
    data = json.loads(raw or "{}")
    if isinstance(data, dict):
        return data.get("items", [])
    return data if isinstance(data, list) else []


def mc_get_task(task_id: str) -> dict:
    raw = run([MC_CLIENT, "get-task", task_id])
    data = json.loads(raw or "{}")
    return data if isinstance(data, dict) else {}


def mc_update_task(task_id: str, *, status: str | None = None, comment: str | None = None,
                   fields: dict | None = None, dry_run: bool = False) -> None:
    if dry_run:
        return
    cmd = [MC_CLIENT, "update-task", task_id]
    if status:
        cmd += ["--status", status]
    if comment:
        cmd += ["--comment", comment]
    if fields is not None:
        cmd += ["--fields", json.dumps(fields)]
    run(cmd, timeout=30)


def load_gateway_token() -> str:
    token = os.environ.get("MC_GATEWAY_TOKEN", "").strip()
    if token:
        return token
    data = json.loads(Path(OPENCLAW_CONFIG).read_text(encoding="utf-8"))
    token = data.get("gateway", {}).get("auth", {}).get("token")
    if not token:
        raise RuntimeError("gateway token not found")
    return token


def wake_luna(message: str, dry_run: bool = False) -> str:
    idempotency_key = f"judge-{int(time.time())}"
    if dry_run:
        return idempotency_key
    params = json.dumps({"message": message, "idempotencyKey": idempotency_key})
    run(
        [
            OPENCLAW_BIN,
            "gateway",
            "call",
            "--url",
            GATEWAY_URL,
            "--token",
            load_gateway_token(),
            "--json",
            "--params",
            params,
            "agent",
        ],
        timeout=25,
    )
    return idempotency_key


def ensure_artifact(relative_path: str, title: str, task_id: str, phase: str, description: str) -> str:
    if not relative_path:
        relative_path = plan_artifact_path(task_id, phase)
    path = WORKSPACE / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(
            "\n".join(
                [
                    f"# {title}",
                    "",
                    f"- Task ID: {task_id}",
                    f"- Phase: {phase}",
                    f"- Generated by: judge-loop-worker",
                    f"- Generated at: {to_iso()}",
                    "",
                    "## Original Description",
                    description or "(sem descricao)",
                    "",
                    "## Required Output",
                    "- Objective validation criteria",
                    "- Explicit decision or task specification",
                    "- References to files/tests used",
                    "",
                ]
            )
            + "\n",
            encoding="utf-8",
        )
    return relative_path


def build_message(task: dict, phase: str, artifact_path: str) -> str:
    task_id = str(task.get("id", ""))
    title = str(task.get("title", "(sem titulo)"))
    description = str(task.get("description", "") or "")
    fields = task_fields(task)
    workflow = task_workflow(task)
    validation = fields.get("mc_validation_artifact", "")
    test_report = fields.get("mc_test_report_artifact", "")

    if workflow == "dev_loop_v1" and phase == "luna_task_planning":
        return f"""Judge loop acionado para PLANEJAMENTO inicial.\n\nTask: {title}\nMC Task ID: {task_id}\nArtifact alvo: {artifact_path}\nCanal operacional: {PRIMARY_CHANNEL}\n\nVoce deve executar AGORA:\n1. Ler a descricao da task.\n2. Escrever o TaskSpec/brief no artifact `{artifact_path}`.\n3. Atualizar o MC card para `in_progress` com `mc_phase=luan_plan_elaboration` usando `mc-task-update.sh` ou `mc-client.sh`.\n4. Incluir criterios objetivos de validacao no artifact.\n\nDescricao original:\n{description[:3000]}\n"""

    if workflow == "dev_loop_v1" and phase == "luna_plan_validation":
        return f"""Judge loop acionado para VALIDACAO DE PLANO.\n\nTask: {title}\nMC Task ID: {task_id}\nPlan artifact: {artifact_path}\n\nVoce deve executar AGORA:\n1. Ler o plano em `{artifact_path}`.\n2. Aprovar ou rejeitar o plano neste turno.\n3. Se aprovar: mover para `in_progress` com `mc_phase=luan_execution_and_tests`.\n4. Se rejeitar: mover para `in_progress` com `review_reason` explicito para voltar a `luan_plan_elaboration`.\n5. Se depender do humano: mover para `awaiting_human` com `review_reason`.\n"""

    if workflow == "dev_loop_v1" and phase == "luna_final_validation":
        return f"""Judge loop acionado para VALIDACAO FINAL.\n\nTask: {title}\nMC Task ID: {task_id}\nValidation artifact: {validation or artifact_path}\nTest report: {test_report or '(nao informado)'}\n\nVoce deve executar AGORA:\n1. Revisar os arquivos modificados.\n2. Rodar os testes relevantes.\n3. Registrar a decisao final no artifact `{validation or artifact_path}`.\n4. Se aprovado: marcar `done`.\n5. Se reprovado: marcar `in_progress` com `review_reason` para voltar a `luan_execution_and_tests`.\n6. Se precisar de decisao humana: marcar `awaiting_human` com `review_reason`.\n"""

    return f"""Judge loop acionado para REVIEW legado/direct_exec.\n\nTask: {title}\nMC Task ID: {task_id}\nReview artifact: {artifact_path}\n\nVoce deve executar AGORA:\n1. Revisar a entrega do executor.\n2. Validar criterios objetivos e testes.\n3. Registrar a decisao no artifact `{artifact_path}`.\n4. Se aprovado: marcar `done`.\n5. Se reprovado: devolver para `in_progress` com `review_reason`.\n\nDescricao original:\n{description[:3000]}\n"""


def select_candidates(tasks: list[dict], task_id: str | None = None) -> list[dict]:
    selected: list[dict] = []
    for task in tasks:
        if task_id and str(task.get("id", "")).strip() != task_id:
            continue
        if not is_actionable_review_task(task):
            continue
        workflow = normalize_workflow(task_fields(task).get("mc_workflow") or "direct_exec")
        phase = task_phase(task)
        owner = task_phase_owner(task)
        if workflow == "dev_loop_v1" and phase not in LUNA_REVIEW_PHASES:
            continue
        if workflow == "dev_loop_v1" and owner != "luna":
            continue
        selected.append(task)
    selected.sort(key=lambda item: item.get("updated_at", item.get("created_at", "")), reverse=True)
    return selected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--task-id")
    parser.add_argument("--limit", type=int, default=1)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    metrics = load_metrics(METRICS_FILE)
    metrics_record_cron(metrics, "judge-loop-worker", "ok")

    tasks = mc_list_tasks()
    candidates = select_candidates(tasks, task_id=args.task_id)
    results = []

    for task in candidates[: args.limit]:
        if is_claim_active(task):
            continue
        phase = task_phase(task)
        fields = task_fields(task)
        task_id = str(task.get("id", ""))
        title = str(task.get("title", "(sem titulo)"))
        description = str(task.get("description", "") or "")
        workflow = task_workflow(task)

        if workflow == "dev_loop_v1":
            artifact_key = "mc_plan_artifact" if phase != "luna_final_validation" else "mc_validation_artifact"
        else:
            artifact_key = "mc_validation_artifact"

        artifact_path = ensure_artifact(
            str(fields.get(artifact_key) or plan_artifact_path(task_id, phase)),
            title,
            task_id,
            phase,
            description,
        )

        claim = claim_review(task, "judge-loop-worker", lease_minutes=LEASE_MINUTES)
        claim_fields = dict(claim["fields"])
        claim_fields[artifact_key] = artifact_path
        comment = f"[judge-loop] claimed {phase} for Luna. artifact={artifact_path}"
        mc_update_task(task_id, status=claim["status"], comment=comment, fields=claim_fields, dry_run=args.dry_run)

        message = build_message(task, phase, artifact_path)
        idempotency_key = wake_luna(message, dry_run=args.dry_run)

        metrics_increment(metrics, "review_claims")
        metrics_increment(metrics, "actionable_review_claims")
        metrics_increment(metrics, "judge_wakeups")
        metrics_record_phase_transition(metrics, task_id, phase)
        results.append(
            {
                "task_id": task_id,
                "phase": phase,
                "workflow": workflow,
                "artifact_path": artifact_path,
                "claim_expires_at": claim_fields.get("mc_claim_expires_at"),
                "idempotency_key": idempotency_key,
            }
        )

    save_metrics(METRICS_FILE, metrics)
    if args.json:
        print(json.dumps({"results": results}, ensure_ascii=False, indent=2))
    else:
        for item in results:
            print(f"{item['task_id'][:8]} {item['phase']} {item['artifact_path']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
