# Production Micro Test — prod-001
# Real CLOB orders with $25 capital and minimum order sizes.
# ⚠️  DO NOT START without funded wallet (POL + USDC.e)

run_id: "prod-001"
mode: "production"
duration_hours: 24
hypothesis: "production-micro-test"
initial_balance: 25

params:
  quote_interval_s: 5.0      # slower than paper (rate limit friendly)
  default_order_size: 5       # minimum Polymarket order size
  default_half_spread_bps: 50
  gamma_risk_aversion: 0.3
  kill_switch_max_drawdown_pct: 20.0   # $5 loss = halt
  kill_switch_alert_pct: 10.0          # $2.50 loss = alert
  initial_on_chain_balance: 232.106    # USDC.e when trading started (2026-02-28)
  markets:
    - "0x561cd8d035bac38ed04e23d7882a126da38d7ead9d6679f722ad62c0c9d54ad2"

success_criteria:
  pnl_positive: false          # not expected to be profitable yet
  max_drawdown_pct: 20.0
  data_collection_hours: 8     # minimum hours needed for valid param extraction

unwind:
  enabled: true
  max_time_seconds: 60
  strategies:
    normal_shutdown: aggressive    # best_bid/ask
    kill_switch: sweep             # mid - 5%
    crash_recovery: hold           # don't unwind, adopt
  dust_threshold_shares: 5         # min order size on Polymarket
  merge_enabled: true              # try CTF merge before selling
  progressive_pricing:
    attempt_1_offset_pct: 0        # at market
    attempt_2_offset_pct: 2        # 2% worse
    attempt_3_offset_pct: 5        # 5% worse (last resort)
  alert_on_orphan: true            # notify if unwind fails
